version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: your_strong_user_password
    command: --skip-networking=0 --bind-address=0.0.0.0
    volumes:
      - /docker/mariadb/data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your_strong_root_password
    depends_on:
      - mariadb
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /docker/nginx/html:/usr/share/nginx/html:ro
      - /docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - my_network

volumes: {}

networks:
  my_network:
